name: Create a comment on new issues
on:
  issues:
    type: [opened]
jobs:
  comment-with-action:
  runs-on: ubuntu-latest
    - name: "dump github context"
      run: echo '${{ toJSON(github.event) }}' | jk
      shell: bash
    
    
  
